openapi: 3.0.0

info:
  title: Report Service API
  description: This server receives and stores PING results, and provides aggregated reports.
  version: 0.0.0

servers:
- url: http://{server-endpoint}/{api-version}
  description: report service server (internal)
  variables:
    server-endpoint:
      enum:
        - report-service-api
        - 127.0.0.1:8000
      default: 127.0.0.1:8000
    api-version:
      default: v1

paths:
  /health:
    get:
      description: the path for checking the API health
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: ok
